"""init migration

Revision ID: 570d90bc3c36
Revises: 
Create Date: 2024-04-07 16:51:13.052491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570d90bc3c36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('access', sa.String(length=2000), nullable=False),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.Column('refresh', sa.String(length=2000), nullable=True),
    sa.Column('type', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squares')
    op.drop_table('scores')
    op.drop_table('users')
    # ### end Alembic commands ###
