"""init

Revision ID: 861bcdbf8f87
Revises: 
Create Date: 2024-02-28 00:26:13.922097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861bcdbf8f87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.Text(length=2000), nullable=False),
    sa.Column('refresh_id', sa.Text(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
