"""restructure

Revision ID: ffb5b9f5da5d
Revises: 861bcdbf8f87
Create Date: 2024-02-28 00:34:22.625024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb5b9f5da5d'
down_revision = '861bcdbf8f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('api_tokens_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'api_tokens', ['id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_foreign_key('api_tokens_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
