"""add client credentials key

Revision ID: 025896438e33
Revises: 83464a5898b8
Create Date: 2024-08-26 19:20:04.598180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025896438e33'
down_revision = '83464a5898b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_key',
    sa.Column('access_token', sa.String(length=2000), nullable=True),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('token_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_key')
    # ### end Alembic commands ###
