"""change all instances of mode to ruleset

Revision ID: 0608eea56da8
Revises: f2d608766b43
Create Date: 2024-04-30 19:11:05.671898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0608eea56da8'
down_revision = 'f2d608766b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruleset', sa.String(length=32), nullable=True))
        batch_op.drop_column('mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('ruleset')

    # ### end Alembic commands ###
