"""add mode to scores

Revision ID: 304ff256a9e2
Revises: 4c650b5deffc
Create Date: 2024-04-27 19:28:13.562064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304ff256a9e2'
down_revision = '4c650b5deffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
