"""change total_hits to note_count for consistency

Revision ID: 3b66774d86f3
Revises: dd6546f67e90
Create Date: 2024-08-07 14:25:28.072557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b66774d86f3'
down_revision = 'dd6546f67e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', sa.BigInteger(), nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', sa.BigInteger(), nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', sa.BigInteger(), nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', sa.BigInteger(), nullable=True))
        batch_op.drop_column('total_hits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('note_count')

    # ### end Alembic commands ###
