"""add streak_counted to rulesets

Revision ID: 4b7a120086aa
Revises: ef8700441a51
Create Date: 2024-09-24 20:44:25.163390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7a120086aa'
down_revision = 'ef8700441a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_counted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_counted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_counted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_counted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_counted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.drop_column('streak_counted')

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.drop_column('streak_counted')

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.drop_column('streak_counted')

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.drop_column('streak_counted')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('streak_counted')

    # ### end Alembic commands ###
