"""correct datetime in scores

Revision ID: 4c650b5deffc
Revises: 02d2186c01ab
Create Date: 2024-04-22 21:25:49.005790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c650b5deffc'
down_revision = '02d2186c01ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
