"""rank -> global_rank

Revision ID: 540e5abf4bae
Revises: 6d3d7529d554
Create Date: 2024-04-17 20:34:23.053864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '540e5abf4bae'
down_revision = '6d3d7529d554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_rank', sa.Integer(), nullable=True))
        batch_op.drop_column('rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('global_rank')

    # ### end Alembic commands ###
