"""expires in -> at

Revision ID: 56b4a5cfd25a
Revises: 025896438e33
Create Date: 2024-08-26 19:52:10.339433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56b4a5cfd25a'
down_revision = '025896438e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('expires_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_in', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
