"""token attributes in User -> original names

Revision ID: 57c6bb5a00cc
Revises: f95e53fa6d2f
Create Date: 2024-04-19 17:13:06.082422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57c6bb5a00cc'
down_revision = 'f95e53fa6d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('expires_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('token_type', sa.String(length=6), nullable=True))
        batch_op.drop_column('expires')
        batch_op.drop_column('access')
        batch_op.drop_column('type')
        batch_op.drop_column('refresh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh', mysql.VARCHAR(length=2000), nullable=True))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('access', mysql.VARCHAR(length=2000), nullable=True))
        batch_op.add_column(sa.Column('expires', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('token_type')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('expires_in')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
