"""add a bunch of attributes to scores, more on the way

Revision ID: 5b0654bce2a5
Revises: 304ff256a9e2
Create Date: 2024-04-27 20:07:16.453878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0654bce2a5'
down_revision = '304ff256a9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playtime', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('count_300', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_100', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_50', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_geki', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_katu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_miss', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_combo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('max_combo')
        batch_op.drop_column('count_miss')
        batch_op.drop_column('count_katu')
        batch_op.drop_column('count_geki')
        batch_op.drop_column('count_50')
        batch_op.drop_column('count_100')
        batch_op.drop_column('count_300')
        batch_op.drop_column('playtime')

    # ### end Alembic commands ###
