"""rm refresh expiry

Revision ID: 6287457b735c
Revises: 533f246779fc
Create Date: 2024-08-26 21:52:26.047611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6287457b735c'
down_revision = '533f246779fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', mysql.VARCHAR(length=2000), nullable=True))

    # ### end Alembic commands ###
