"""add default mode to users

Revision ID: 67517cab1350
Revises: b882dddbd83f
Create Date: 2024-05-02 13:38:07.178320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67517cab1350'
down_revision = 'b882dddbd83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playmode', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('playmode')

    # ### end Alembic commands ###
