"""add rank to users

Revision ID: 6d3d7529d554
Revises: 570d90bc3c36
Create Date: 2024-04-15 17:25:45.934153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d3d7529d554'
down_revision = '570d90bc3c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.alter_column('access',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('rank')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
