"""change all instances of note_count to total_hits to align with api

Revision ID: 83464a5898b8
Revises: 3b66774d86f3
Create Date: 2024-08-07 14:28:39.530842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83464a5898b8'
down_revision = '3b66774d86f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', sa.Integer(), nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', sa.BigInteger(), nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', sa.BigInteger(), nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', sa.BigInteger(), nullable=True))
        batch_op.drop_column('note_count')

    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hits', sa.BigInteger(), nullable=True))
        batch_op.drop_column('note_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_hits')

    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_hits')

    # ### end Alembic commands ###
