"""add artist to beatmapsets

Revision ID: 8aead6f72dc9
Revises: a461d6343576
Create Date: 2024-05-11 19:28:10.379063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aead6f72dc9'
down_revision = 'a461d6343576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist_unicode', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.drop_column('artist_unicode')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###
