"""play_time Interval -> Integer

Revision ID: 8aee56941926
Revises: f83e2d818815
Create Date: 2024-05-02 01:10:02.515759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8aee56941926'
down_revision = 'f83e2d818815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.alter_column('play_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.alter_column('play_time',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
