"""increase token char limit from 1000 to 2000

Revision ID: 928e14536df0
Revises: 57c6bb5a00cc
Create Date: 2024-04-21 16:34:19.550478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '928e14536df0'
down_revision = '57c6bb5a00cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=2000), nullable=False),
    sa.Column('token_type', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')
        batch_op.drop_column('expires_in')
        batch_op.drop_column('token_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_type', mysql.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('expires_in', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('access_token', mysql.VARCHAR(length=2000), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', mysql.VARCHAR(length=2000), nullable=True))

    op.drop_table('tokens')
    # ### end Alembic commands ###
