"""test

Revision ID: 97fcd45ffd6c
Revises: d99c6b66e3f8
Create Date: 2024-05-02 01:38:10.164762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97fcd45ffd6c'
down_revision = 'd99c6b66e3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_statistics',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ruleset', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('play_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('play_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ranked_score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tokens.user_id'], name='daily_statistics_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
