"""move various attributes from beatmapset to beatmap

Revision ID: 99a73da9afab
Revises: 8adcebc4acef
Create Date: 2024-04-30 18:45:59.568920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a73da9afab'
down_revision = '8adcebc4acef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('total_length', sa.Integer(), nullable=True))

    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.drop_column('mode')
        batch_op.drop_column('difficulty_rating')
        batch_op.drop_column('total_length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_length', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('difficulty_rating', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('mode', mysql.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('beatmaps', schema=None) as batch_op:
        batch_op.drop_column('total_length')
        batch_op.drop_column('mode')
        batch_op.drop_column('difficulty_rating')

    # ### end Alembic commands ###
