"""accuracy now string

Revision ID: 9cc077809ef5
Revises: 28bb16522a9a
Create Date: 2024-11-27 16:50:59.902180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cc077809ef5'
down_revision = '28bb16522a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('accuracy',
               existing_type=sa.String(length=16),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
