"""change max user length from 15 to 18

Revision ID: a461d6343576
Revises: ceeffaabfa31
Create Date: 2024-05-11 17:20:10.229621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a461d6343576'
down_revision = 'ceeffaabfa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.alter_column('creator',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=True)

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=True)

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=True)

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=True)

    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.alter_column('creator',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
