"""refactor

Revision ID: b882dddbd83f
Revises: 97fcd45ffd6c
Create Date: 2024-05-02 01:38:38.370233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b882dddbd83f'
down_revision = '97fcd45ffd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleset', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('ranked_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tokens.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'ruleset', 'start_date', name='daily_statistics_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_statistics')
    # ### end Alembic commands ###
