"""parent class from users to tokens

Revision ID: bcf74706924a
Revises: 217ff31b55a8
Create Date: 2024-04-29 12:09:27.093835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf74706924a'
down_revision = '217ff31b55a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('scores_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tokens', ['user_id'], ['user_id'])

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint('tokens_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tokens', ['id'], ['user_id'])

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.drop_constraint('users_catch_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tokens', ['id'], ['user_id'])

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.drop_constraint('users_mania_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tokens', ['id'], ['user_id'])

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.drop_constraint('users_osu_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tokens', ['id'], ['user_id'])

    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.drop_constraint('users_taiko_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tokens', ['id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_taiko', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_taiko_ibfk_1', 'users', ['id'], ['id'])

    with op.batch_alter_table('users_osu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_osu_ibfk_1', 'users', ['id'], ['id'])

    with op.batch_alter_table('users_mania', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_mania_ibfk_1', 'users', ['id'], ['id'])

    with op.batch_alter_table('users_catch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_catch_ibfk_1', 'users', ['id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_foreign_key('tokens_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scores_ibfk_3', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
