"""change card to slimcover

Revision ID: ceeffaabfa31
Revises: db02e4ec6119
Create Date: 2024-05-11 16:42:48.495157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceeffaabfa31'
down_revision = 'db02e4ec6119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slimcover', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('slimcover_2x', sa.String(length=255), nullable=True))
        batch_op.drop_column('card')
        batch_op.drop_column('card_2x')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('beatmapsets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_2x', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('card', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('slimcover_2x')
        batch_op.drop_column('slimcover')

    # ### end Alembic commands ###
