"""add composite key for daily_statistics, refactor

Revision ID: d99c6b66e3f8
Revises: 8aee56941926
Create Date: 2024-05-02 01:28:11.817634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd99c6b66e3f8'
down_revision = '8aee56941926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.alter_column('ruleset',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('ruleset',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
