"""expires_in (int) -> expires_at (datetime)

Revision ID: eee5e9da97fc
Revises: 928e14536df0
Create Date: 2024-04-22 10:27:10.696707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eee5e9da97fc'
down_revision = '928e14536df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('expires_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_in', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
