"""add overall streaks to user

Revision ID: ef8700441a51
Revises: 5c8af822061a
Create Date: 2024-09-02 12:02:15.575687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8700441a51'
down_revision = '5c8af822061a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak_longest', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('streak_longest')
        batch_op.drop_column('streak_current')

    # ### end Alembic commands ###
