"""change all instances of mode to ruleset

Revision ID: f2d608766b43
Revises: 99a73da9afab
Create Date: 2024-04-30 19:10:34.757019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2d608766b43'
down_revision = '99a73da9afab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruleset', sa.String(length=16), nullable=True))
        batch_op.drop_column('mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', mysql.VARCHAR(length=16), nullable=True))
        batch_op.drop_column('ruleset')

    # ### end Alembic commands ###
