"""make daily statistic columns consistent, add ranked_score and total_score

Revision ID: f83e2d818815
Revises: be0606a292a6
Create Date: 2024-05-01 17:34:45.501953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f83e2d818815'
down_revision = 'be0606a292a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_time', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ranked_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))
        batch_op.drop_column('notecount')
        batch_op.drop_column('playtime')
        batch_op.drop_column('playcount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playcount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('playtime', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('notecount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_score')
        batch_op.drop_column('ranked_score')
        batch_op.drop_column('note_count')
        batch_op.drop_column('play_count')
        batch_op.drop_column('play_time')

    # ### end Alembic commands ###
